name: Build project
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🙃
        uses: actions/checkout@v4

      - name: Set up JDK 21 🛠
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Maven 3.9.6 🔮
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6

      - name: Compile project ⚙
        run: mvn -B compile --file pom.xml

      - name: Install project ⚙
        run: mvn -B install --file pom.xml
